name: 构建core镜像

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取官方KubeSphere镜像，并保存到私有仓库
      run: |
        docker pull kubesphere/ks-installer:v3.3.1
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-beijing.aliyuncs.com
        docker tag kubesphere/ks-installer:v3.3.1 registry.cn-beijing.aliyuncs.com/marbleqi/ks-installer:v3.3.1
        docker push registry.cn-beijing.aliyuncs.com/marbleqi/ks-installer:v3.3.1
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
